# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Kafka properties.
# tag::kafkaBootstrapServers[]
# tag::kafkaDefaultTopic[]
spring:
  kafka:
    bootstrap-servers:
    - localhost:9092
# end::kafkaBootstrapServers[]
    template:
      default-topic: tacocloud.orders.topic
# end::kafkaDefaultTopic[]
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer