server:
  port: 8081
spring:
  profiles:
    active: jms-template
---
spring:
  profiles: jms-template, jms-listener,rabbitmq-template,rabbitmq-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: artemis
    password: artemis
    embedded:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    template:
#      receive-timeout: 10000
# receive-timeout单位毫秒
---
spring:
  profiles: kafka-listener
    
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos
      
      
      
      
      